### ISSUE TITLE
How to kill web-page-replay subprocess properly?

### ISSUE THREAD

**Issue by colin-scott** [chromium/web-page-replay#35]
Hey,

I'm writing a script to programmatically start and then shutdown web-page-replay.

I'm having difficulty properly shutting down web-page-replay. In particular, when I:
- spawn a web-page-replay subprocess
- send SIGTERM to the web-page-replay process
- call wait() on the killed subprocess's pid

it appears that web-page-replay subprocess does not exit properly. As a result, /etc/resolv.conf is still set to 127.0.0.1.

Calling wait() should, in theory, clean up all of web-page-replay's children. But, apparently this isn't happening?

I also tried sending SIGTERM to web-page-replay's process group, but this didn't work either. 

What's the proper way to shutdown a web-page-replay subprocess?

Thanks!
-Colin

**Comment by desmondtam** [comment]
As a reference, I added a few lines to replay.py to allow the signal interrupt to be handled properly.  I derived the code from a few other examples.  This allowed child processes to be shutdown gracefully and the wpr file to be written out.

# START DT EDITS
import signal
import sys
 
def signal_term_handler(signal, frame):
    print 'got SIGINT'
    logging.info('Shutting down.')
    if options.record:
       http_archive.Persist(replay_filename)
       logging.info('Saved %d responses to %s', len(http_archive), replay_filename)
       sys.exit(0)
 
signal.signal(signal.SIGINT, signal_term_handler)

# END DT EDITS
