### ISSUE TITLE
Implements --log_all_requests in replay.py

### ISSUE THREAD

**Issue by gabadie** [chromium/web-page-replay#61]
Hello,

We need a command line argument in replay.py that would log absolutely all {HTTP,HTTPS,DNS} requests. Can we have this?

Thanks!

**Comment by nedn** [comment]
We are pretty swamped currently, but I can review patches. You can first look into the rule_parser structure in web-page-replay that allows customizing record/replay rules. One rule can be use here is "logging rule" that log the requests.

**Comment by gabadie** [comment]
Actually, they are all logged, only need to set the logging level to debug. Thanks! =)
