### ISSUE TITLE
WPR certificate problems when using WPR to record a Chrome Telemetry pageset

### ISSUE THREAD

**Issue by zeptonaut** [chromium/web-page-replay#75]
When @nedn tried to rerecord the Chrome Telemetry `v8_infinite_scroll_ignition` page set from the Chromium src/ directory with 

```
./tools/perf/record_wpr v8_infinite_scroll_ignition --browser=android-system-chrome --story-filter=discourse
```

(with an Android Galaxy S5 or Nexus 5 connected) he got an error that looked like this:

![screen](https://cloud.githubusercontent.com/assets/1407397/15336871/a8151aba-1c46-11e6-8e02-826ca1268656.png)

Any idea what might be going wrong?

**Comment by zeptonaut** [comment]
Note: it looks like this problem may be the same as the one reported 9 months ago [here](https://groups.google.com/a/chromium.org/forum/?nomobile=true#!topic/telemetry/cyz6lY6W9CU).

**Comment by nedn** [comment]
Could not reproduce this problem ~_~
