### ISSUE TITLE
Script injection broken by 1362f49

### ISSUE THREAD

**Issue by nickie** [chromium/web-page-replay#77]
Here's how to reproduce this:

1.  On one shell, run:
    ```
    ./replay.py --port=4080 --ssl_port=4443 --no-dns_forwarding --record foo.wpr
    ```

2.  On a second shell, run:
    ```
    timeout 10 $MY_FAVORITE/chrome --ignore-certificate-errors \
      --host-resolver-rules="MAP *:80 localhost:4080, MAP *:443 localhost:4443, EXCLUDE localhost" \
      'https://www.google.de/search?q=v8'
    ```

3.  Ctrl-C the `replay.py` command on the first shell.

    At this point, you can verify that some CHUNK_BOUNDARY are (probably) not being properly handled by running:
    ```
    ./httparchive.py cat foo.wpr | grep BOUNDARY | head -2
    ```

4.  Prepare a simple script to be injected.  Run:
    ```
    cat > inj.js <<EOF
    (function() {
      window.addEventListener("load", function() {
        alert("Running the injected script!");
      });
    })();
    EOF
    ```

5.  On the first shell, run:
    ```
    ./replay.py --port=4080 --ssl_port=4443 --no-dns_forwarding --inject_scripts=deterministic.js,inj.js --use_closest_match foo.wpr
    ```

6. On the second shell, run:
    ```
    $MY_FAVORITE/chrome --ignore-certificate-errors \
      --host-resolver-rules="MAP *:80 localhost:4080, MAP *:443 localhost:4443, EXCLUDE localhost" \
      'https://www.google.de/search?q=v8'
    ```

At step 6, you should see the alert message "Running the injected script!", but you will not.

If you repeat step 6 after you have checkout out commit d23e5a8, it will work as expected.  The commit that revealed the problem (I believe, not the one that caused it) is 1362f49.

**Comment by nickie** [comment]
Fix uploaded here: https://codereview.appspot.com/297440043/

**Comment by nedn** [comment]
Thanks nickie for the fix!
