### ISSUE TITLE
Dummynet issue

### ISSUE THREAD

**Issue by vrege** [chromium/web-page-replay#88]
The suggested Dummynet installation steps don't work - I'm getting an error when I download the source and run make:

error: argument to ‘sizeof’ in ‘memset’ call is the same expression as the destination; did you mean to dereference it? [-Werror=sizeof-pointer-memaccess]
   bzero(fs, sizeof(fs)); /* safety */
                   ^
/home/vrege/Downloads/ipfw3-20120610/dummynet2/missing.h:139:34: note: in definition of macro ‘bzero’
 #define bzero(s, n) memset(s, 0, n)

**Comment by nedn** [comment]
We recommend users to use https://github.com/WPO-Foundation/tsproxy for traffic shaping instead.
