### ISSUE TITLE
Drivers available for win 10 ?

### ISSUE THREAD

**Issue by rahulchaphalkar** [chromium/web-page-replay#89]
I know this tool has experimental support for windows, but do you know if drivers are available for windows 10? I tried the installation steps, and trying to install service with 'have disk' option shows a message saying 'Unable to find any drivers for this device'.

**Comment by nedn** [comment]
We no longer support dummynet. It's recommended for users to use https://github.com/WPO-Foundation/tsproxy for traffic shaping instead.

**Comment by nedn** [comment]
I still need to update the documentation here.
